### ISSUE TITLE
Expected data format

### ISSUE THREAD

**Issue by mattradford** [indgy/LittleBigTable#1]
Hi Ian

Thanks for creating this library, I can see it being very useful as I work with Alpine. I was hoping you could help with formatting returned data.

I've created an example here: https://gist.github.com/mattradford/cd1e36698692c7a2bf38324711b13a25

I'm trying to format data returned from a WordPress REST API endpoint. I've reformatted, adding the response to data and adding the total. I'm not sure what I'm doing wrong though, as LBT isn't picking up this reformatted data. This is probably a n00b JS error, as I'm not that proficient in JS yet.

Thanks
Matt

**Comment by indgy** [comment]
Hi Matt,

Thanks for taking a look at LittleBigTable it's good to see people using it.

I've taken a quick look at what you've done which raises a few interesting insights, but I think that 'out of the box' it will not do what you need it to do. The issue is that LittleBigTable is intended to be used on your own API endpoint where you can craft the expected response. 

I think what you need is some kind of tabular API browser, it may be possible to modify the code to do that but you may be best starting from scratch and copying whatever works out of LittleBigTable.

The docs [Fetching data](https://github.com/indgy/LittleBigTable#fetching-data) shows the response that LittleBigTable expects.

The Wordpress demo data your using is the `data` to iterate through, but it needs the `total` property alongside it, without it LittleBigTable doesn't see it as valid data (it cannot work out pagination) and gives up.

If you can get the response into the right format, e.g. {total: 100, data: [wp post, wp post, wp post]} LittleBigTable could read it. If you have access to PHP you can use the json.php file in the examples folder to do this, you'll need to set it up on a server somewhere. Perhaps you can setup a proxy between your WP data and your LittleBigTable page?

If you do get the data source formatted correctly you should pass your settings as below, it is not possible to override the x-init="init()" but nice try ;) 
```js
let settings = {
    	url: 'http://localhost:8080/json.php',
}
```
Pass settings to LBT like so
```html
<div x-data="LittleBigTable(settings)" x-init="init()">
```

If you want to format the data just create the formatters object in the settings above and give it a property matching a property from your wordpress data:
```js
let settings = {
    	url: 'https://demo.wp-api.org/wp-json/wp/v2/posts',
        formatters: {
                status: function(value, row) {
                     return `<strong>${value}</strong>`;
                },
                link: function(value, row) {
                     return `<a href="${value}">${value}</a>`;
                }
        }

}
```

Hope it helps!

Ian

**Comment by mattradford** [comment]
Hi Ian

Thanks for your reply 👍 We had a developer roundtable on Thursday at @10degrees and worked on my LBT issue as a group. We got it working using `x-init="initLBT()"` and the following:

```
function initLBT() {
            url = 'https://demo.wp-api.org/wp-json/wp/v2/posts?per_page=100';
            return fetch(url)
                .then(response => response.json())
                .then(response => {
                    this.rows = response;
                    this.params.total = response.length;
                });
        }
```

That gave us an initial listing of posts from the API, but on working through the rest of the code we realised that we were going to have further problems overriding `fetch`, `addRow` and the use of parameters.

However, it was a fun exercise and has given us some ideas. Using a library like this to provide useful functionality is one of joys of Alpine. I've forked your repo and if I get some time will see where I get to with LittleBigWordPressTable :)

Thanks again for your work and kind reply.
Cheers, Matt
